[package]
name = "rs-png-decoder-rewrite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "png_decoder"

[dependencies]
rustc-hash = { version = "1.1.0" }

[features]
